-
  CNN:
    activation: leaky_relu
    batchNorm:
      - 1
      - 1
      - 1
    denseUnit:
      - 1024
      - 512
    kernels:
      - 3
      - 3
      - 3
    layers:
      - 16
      - 32
      - 64
    maxPool:
      - 1
      - 1
      - 0
    stride:
      - 1
      - 1
      - 1
  Query_Sequential:
    - 128
    - 256
  general:
    displayNet: false
    seed: 0
  training:
    attention:
      - true
      - false
    2CNN: false
    fixed_samples: true
    bce : 0.1
    cv: 25
    cat_qp: diff
    decay: 1.e-7
    dropRate: 0
    learning_rate: 5.e-2
    init_epoch: -1
    train: true
    batch_size: 256
    passages_per_query: 200
  note: '试图增加layers'
